version: '3.8'
services:
  backend:
    build: ./services/backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://username:password@db/dbname
    volumes:
      - ./services/backend:/app    
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./services/backend/postgres_data
